AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple RESTful API endpoint using Amazon API Gateway.
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: s3://playground-sam-20230928-becca/5f7e233c44da1bb4ffa6b8365a0e5f55
      Description: A simple RESTful API endpoint using Amazon API Gateway.
      Timeout: 10
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
