AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple RESTful API endpoint using Amazon API Gateway.
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_gateway/app.py.lambda_function.lambda_handler
      CodeUri: s3://playground-sam-20230928-becca/4cce234ae9e87e7e3e708927ad32a38d
      Description: A simple RESTful API endpoint using Amazon API Gateway.
      Timeout: 10
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
