AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
        REGION_NAME:
          Ref: AWS::Region
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: s3://playground-sam-20230928-becca/fbc950858aacea79847dbe518470d776
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      Timeout: 10
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
